name: dashtransit
network: dashtransit
services:
- name: dashtransit
  project: src/DashTransit.App/DashTransit.App.csproj
  liveness:
    failureThreshold: 30
    http:
      path: /health/live
  readiness:
    http:
      path: /health/ready
  bindings:
  - protocol: http
    port: 5149
- name: rabbitmq
  image: rabbitmq:3-management-alpine
  bindings:
  - name: amqp
    port: 5672
    protocol: amqp
    connectionString: amqp://guest:guest@localhost:${port}
  - name: management
    port: 15672
    containerPort: 15672
    protocol: http
  volumes:
  - source: ./.volumes/rabbit
    target: /var/lib/rabbitmq
  env:
  - RABBITMQ_NODENAME=rabbit@rabbitmq
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest
  bindings:
  - port: 1433
    protocol: tcp
    connectionString: "Server=${host},${port};Database=dashtransit;User Id=sa;Password=${env:SA_PASSWORD};"
  volumes:
  - source: ./.volumes/sql/data
    target: /var/opt/mssql/data
  - source: ./.volumes/sql/log
    target: /var/opt/mssql/log
  env:
  - ACCEPT_EULA=Y
  - SA_PASSWORD=P@ssword123
- name: postgres
  image: postgres
  bindings:
  - port: 5432
    protocol: tcp
    connectionString: "User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};Host=${host};Port=${port};Database=${env:POSTGRES_DB};"
  volumes:
  - source: ./.volumes/pg
    target: /var/lib/postgresql/data
  env:
  - ACCEPT_EULA=Y
  - POSTGRES_PASSWORD=P@ssword123
  - POSTGRES_USER=sa
  - POSTGRES_DB=dashtransit
  - PGDATA=/var/lib/postgresql/data/pgdata