USE dashtransit;
GO

-- BEGIN TRY
--     DROP FULLTEXT CATALOG MessageCatalog;
-- END TRY
-- BEGIN CATCH
--     PRINT 'Full text catalog not there'
-- END CATCH

-- CREATE FULLTEXT CATALOG MessageCatalog;
-- GO

DROP TABLE IF EXISTS Faults;
DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages
(
    MessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    Timestamp DATETIMEOFFSET NOT NULL,
    Content VARCHAR(MAX) NOT NULL,
) AS NODE;

--CREATE FULLTEXT INDEX ON Messages(Content, Type)
--KEY INDEX IDX_Id ON MessageCatalog

CREATE TABLE Faults
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    MessageId UNIQUEIDENTIFIER NOT NULL,
    Exception VARCHAR(MAX) NOT NULL,
    StackTrace VARCHAR(MAX),
    Source VARCHAR(1000),
    CONSTRAINT FK_MessageFault FOREIGN KEY (MessageId)
    REFERENCES Messages(MessageId)
) AS NODE;

DROP TABLE IF EXISTS Endpoints;
CREATE TABLE Endpoints
(
    Id INTEGER PRIMARY KEY IDENTITY(1,1),
    Uri VARCHAR(512)
) AS NODE;

DROP TABLE IF EXISTS MessageTypes;
CREATE TABLE MessageTypes
(
    Id INTEGER PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(512)
) AS NODE;

DROP TABLE IF EXISTS ExceptionTypes;
CREATE TABLE ExceptionTypes
(
    Id INTEGER PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(512)
) AS NODE;

DROP TABLE IF EXISTS Initiator;
CREATE TABLE Initiator(ConversationId UNIQUEIDENTIFIER NOT NULL) AS EDGE;

DROP TABLE IF EXISTS Threw;
CREATE TABLE Threw AS EDGE;

DROP TABLE IF EXISTS OfType;
CREATE TABLE OfType AS EDGE;

DROP TABLE IF EXISTS Source;
CREATE TABLE Source AS EDGE;

DROP TABLE IF EXISTS Destination;
CREATE TABLE Destination AS EDGE;
