USE dashtransit;
GO

BEGIN TRY
    DROP FULLTEXT CATALOG MessageCatalog;
END TRY
BEGIN CATCH
    PRINT 'Full text catalog not there'
END CATCH

CREATE FULLTEXT CATALOG MessageCatalog;
GO


DROP TABLE IF EXISTS Faults;
DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages
(
    Id INT IDENTITY(1,1) NOT NULL,
    MessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CorrelationId UNIQUEIDENTIFIER,
    Content VARCHAR(MAX) NOT NULL,
    Type VARCHAR(200) NOT NULL,
    Timestamp DATETIMEOFFSET NOT NULL,
) AS NODE;

CREATE UNIQUE INDEX IDX_Id ON Messages(Id)
--CREATE FULLTEXT INDEX ON Messages(Content, Type)
--KEY INDEX IDX_Id ON MessageCatalog

CREATE TABLE Faults
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    MessageId UNIQUEIDENTIFIER NOT NULL,
    Exception VARCHAR(MAX) NOT NULL,
    StackTrace VARCHAR(MAX),
    Type VARCHAR(200) NOT NULL,
    Source VARCHAR(1000),
    CONSTRAINT FK_MessageFault FOREIGN KEY (MessageId)
    REFERENCES Messages(MessageId)
) AS NODE;

DROP TABLE IF EXISTS Endpoints;
CREATE TABLE Endpoints
(
    Id INTEGER PRIMARY KEY,
    Uri VARCHAR(200)
) AS NODE;

DROP TABLE IF EXISTS Sent;
CREATE TABLE Sent AS EDGE;

DROP TABLE IF EXISTS Recieved;
CREATE TABLE Recieved AS EDGE;
