USE dashtransit;
GO

DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages
(
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Content VARCHAR(MAX),
    Type VARCHAR(200)
) AS NODE;

DROP TABLE IF EXISTS Fault;
CREATE TABLE Fault
(
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Message VARCHAR(MAX),
    Type VARCHAR(200)
) AS NODE;

DROP TABLE IF EXISTS Endpoints;
CREATE TABLE Endpoints
(
    Id INTEGER PRIMARY KEY,
    Uri VARCHAR(200)
) AS NODE;

DROP TABLE IF EXISTS Sent;
CREATE TABLE Sent AS EDGE;

DROP TABLE IF EXISTS Recieved;
CREATE TABLE Recieved AS EDGE;
