name: CI Build

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/DashTransit.App/Dockerfile
          #push: true
          tags: dashtransit:latest
